[package]
name = "pkl-lsp-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Native stdio Language Server Protocol server for PKL"

[[bin]]
name = "pkl-lsp"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
lsp-types.workspace = true
pkl-lsp-core = { path = "../pkl-lsp-core" }
serde_json.workspace = true
tokio.workspace = true
